### ISSUE TITLE
Add a feature that lets users create their own regulations/mapsets through local files

### ISSUE THREAD

**Issue by Zarv** [acc-is-sponge/beat-speedrun-mod#4]
Hey there, not really an issue but more of a suggestion for the mod.

Could it be possible to have users make/use their own regulations and mapsets locally on their PC? I see that the mod already pulls from your github repositories for the regulations/mapsets, but I think allowing a feature or option to have it pull local files would be great as well.

I had the idea of using the current regulation and mapset, but have the time be really long or infinite - turning the mod into a local leaderboard that tracks PP. In order to do this, I would need to edit or create my own regulation json file.

If users could customize or make their own regulations/mapsets, they could have their own personal, resettable local leaderboards if they do not care about uploading scores to Scoresaber / Beatleader / Hitbloq.

I think this would be a really nice feature to add to the mod. I would most certainly be using it to try a few challenges - for example seeing what PP or rank you'd have if you only played 8 stars and below within 30 days, or trying to see how much PP you could get in a week instead of 48 hours.

**Comment by yubrot** [comment]
Yes, it is. I think this mod can be used in that way!

In fact, that functionality is already implemented in this MOD, by...
- Placing the regulation definition to `UserData/BeatSpeedrun/Regulations`, for example `UserData/BeatSpeedrun/Regulations/your-regulation.json`
- Set the regulation options like `["your-regulation.json", "scoresaber/092023.json"]` in the configuration file (`UserData/BeatSpeedrun.json`).

The reason I haven't yet put this feature in a well visible position for users is, that I was looking for a way to emphasize the competitive aspect of it, that various people are speedrunning with the same regulations. Once I make some adjustments, such as explicitly displaying a string like `(local)` on the screen when using local regulations, I will release it as an official feature of this MOD.

**Comment by acc-is-sponge** [comment]
Yes, it is. I think this mod can be used in that way!

In fact, that functionality is already implemented in this MOD, by...
* Placing the regulation definition to `UserData/BeatSpeedrun/Regulations`, for example `UserData/BeatSpeedrun/Regulations/your-regulation.json`
* Set the regulation options like `["your-regulation.json", "scoresaber/092023.json"]` in the configuration file (`UserData/BeatSpeedrun.json`).

The reason I haven't yet put this feature in a well visible position for users is, that I was looking for a way to emphasize the competitive aspect of it, that various people are speedrunning with the same regulations. Once I make some adjustments, such as explicitly displaying a string like `(local)` on the screen when using local regulations, I will release it as an official feature of this MOD. For now this behavior likely to be changed, but I'll provide a feature like this.
